[tools]
bat = "latest"
chezmoi = "latest"
ripgrep = "latest"
neovim = "0.11.1"
node = "latest"     # needed for some Neovim plugins
#rust = "latest"     # needed for codesnap.nvim
op = "latest"
starship = "latest"
lazygit = "latest"
lazydocker = "latest"
fd = "latest"
fx = "latest"
usage = "latest"
